version: '3.9'
services:
  api:
    container_name: food_web
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3055:3055
    environment:
      - MONGO_URI=mongodb://mongo-container/FoobWeb
    networks:
      - a
    depends_on:
      - mongo-container
  mongo-container:
    image: mongo
    restart: always
    container_name: mongo-food-web
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./.docker/mongodb:/data/db
    networks:
      - a

networks:
  a:
    name: a-network
